### ISSUE TITLE
Error when using logger.trace

### ISSUE THREAD

**Issue by craigharman** [tsedio/logger#94]
## Informations

Type | Version
---|---
Bug | 5.15.0

****

## Description
If I user the logger.trace function I get an error message:

```
Error: 
at Function.createStack (/home/pi/test-jig/shared/client/node_modules/@tsed/logger/src/logger/class/Logger.ts:55:27)
at Logger.trace (/home/pi/test-jig/shared/client/node_modules/@tsed/logger/src/logger/class/Logger.ts:126:33)
at TestService.fail (/home/pi/test-jig/releases/20210709093330/client/src/services/TestService.ts:125:21)
at TestService.resetASEConfiguration (/home/pi/test-jig/releases/20210709093330/client/src/services/TestService.ts:236:12)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Replacing .trace with any other logging function (.error, .info, etc) and it works fine.

Ts.ED version: 6.48.5

## Todos

- [x] Example (log, usecase, etc...)
- [x] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
Hello @craigharman 
This is not an error message. I the trace, but I agree the stack trace isn't clean it should print only the concerned line:
```
at TestService.fail (/home/pi/test-jig/releases/20210709093330/client/src/services/TestService.ts:125:21)
at TestService.resetASEConfiguration (/home/pi/test-jig/releases/20210709093330/client/src/services/TestService.ts:236:12)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
I clean the stack.
See you
Romain
